#! /bin/sh

set -e

SERVICE="hector"
DAEMON="${SERVICE}d"
SHELLLIB="${HOME}/src/server/shell-lib"
PARSER="${HOME}/src/server/parse-sh"
declare -i STEP=0
declare -i STEP_FIRST=0
declare -i STEP_LAST=9999
EXECUTE_COMMANDS=""
DIR_ROOT=`pwd`

if [ ! -f ${SHELLLIB} ] ; then
	echo "no shell programming library found"
	exit 1
fi

. ${SHELLLIB}

must_exist ${PARSER}

. ${PARSER}

if [ ! -d build ] ; then
	echo "you must start this script from \`hector' root directory"
	exit 1
fi

JAIL="/home/${SERVICE}/"

conditional_chattr() {
	if [ -d ${1} ] ; then
		chattr -i ${1}/*
	fi
}

conditional_umount() {
	MOUNTED=`awk '/\/home\/hector\/proc/' /proc/mounts`
	if [ "x${MOUNTED}" != "x" ] ; then
		umount -f /home/${SERVICE}/proc
	fi
}

adv ./_deploy/init stop
adv /bin/rm -fr nest
adv mkdir -p nest/etc/conf nest/var/db/keys
adv cp build/${DAEMON}/1exec nest/
adv cp -a ~/usr/lib nest
adv cp -a ~/src/yaal/yaalrc nest/etc/conf/
adv cp -a ~/src/${SERVICE}/hectorrc nest/etc/conf/
adv cp -a ~/var/db/keys/yaal.* nest/var/db/keys/
adv conditional_chattr ${JAIL}/nest "${JAIL}/nest/*"
adv conditional_umount
adv /bin/rm -rf ${JAIL}/*

adv mkdir -p nest/app
HECTOR_SETUP=`readlink ${HOME}/src/${SERVICE}/app/hector.xml`
adv cp -a ${HOME}/src/${SERVICE}/app/${HECTOR_SETUP} nest/app/hector.xml
APPS=`xmlstarlet sel -T -t -m "/hector/applications/application[@load='true']" -o ${HOME}/src/cellar/web/ -v '@symbol' -n ${HOME}/src/${SERVICE}/app/${HECTOR_SETUP}`
adv cp -af ${APPS} nest/app/
for ITEM in nest/app/* ; do
	if [ -f ${ITEM}/interface.xml ] ; then
		APP=`basename ${ITEM}`
		if [ -f ./build/${APP}/1exec ] ; then
			adv /bin/rm -f nest/app/${APP}/activex
			adv cp -f ./build/${APP}/1exec nest/app/${APP}/activex
			adv chmod 644 nest/app/${APP}/activex
		fi
	fi
done
adv mkdir -p ${JAIL}/tmp/hector ${JAIL}/bin

adv mv nest ${JAIL}/
adv cp /bin/bash-minimal ${JAIL}/bin/sh
adv chmod 1757 ${JAIL}/tmp
adv chmod 755 ${JAIL}/tmp/hector
adv chown -R root:root ${JAIL}/nest/
adv chown ${SERVICE}:service ${JAIL}/nest/ ${JAIL}/tmp/hector
adv chmod -R a+rX ${JAIL}/bin ${JAIL}/nest/*
adv makejail ./_deploy/jail-${DAEMON}.py
if [ ! -f ${JAIL}/etc/passwd ] ; then
	echo "Deployment failed!"
	exit 1
fi
adv /bin/rm -f ${JAIL}/nest/x_*
adv "grep service /etc/group > ${JAIL}/etc/group"
adv chattr +i ${JAIL}/nest/*

