#! /bin/sh

set -e

SERVICE="hector"
DAEMON="${SERVICE}d"
SHELLLIB="${HOME}/src/server/shell-lib"
PARSER="${HOME}/src/server/parse-sh"
STEP=0
STEP_FIRST=0
STEP_LAST=9999
EXECUTE_COMMANDS=""
DIR_ROOT=$(pwd)

if [ ! -f ${SHELLLIB} ] ; then
	echo "no shell programming library found"
	exit 1
fi

. ${SHELLLIB}

must_exist ${PARSER}

. ${PARSER}

TARGET="${1}"

if [ "x${TARGET}" != "xdebug" -a "x${TARGET}" != "xrelease" ] ; then
	TARGET="release"
fi

if [ ! -d build ] ; then
	echo "you must start this script from \`hector' root directory"
	exit 1
fi

JAIL="/home/${SERVICE}/"

conditional_immutable_off() {
	if [ -d ${1} ] ; then
		set +e
		chattr -f -R -i "${1}"
		set -e
	fi
}

conditional_immutable_on() {
	if [ -d ${1} ] ; then
		set +e
		chattr -f -R +i "${1}"
		set -e
	fi
}

conditional_umount() {
	MOUNTED=$(awk '/\/home\/hector\/proc/' /proc/mounts)
	if [ "x${MOUNTED}" != "x" ] ; then
		umount -f /home/${SERVICE}/proc
	fi
	MOUNTED=$(awk '/\/home\/hector\/var\/run\/postgresql/' /proc/mounts)
	if [ "x${MOUNTED}" != "x" ] ; then
		umount -f /home/${SERVICE}/var/run/postgresql
	fi
}

unset PS_FORMAT

adv ./_deploy/init stop
adv /bin/rm -fr nest
adv mkdir -p nest/etc/conf nest/var/db/yaal/keys
adv cp build/${TARGET}/${DAEMON}/1exec nest/
adv cp -a ${HOME}/usr/lib nest
adv cp -a ${HOME}/src/yaal/build/${TARGET}/yaalrc nest/etc/conf/
adv cp -a ${HOME}/src/${SERVICE}/hectorrc nest/etc/conf/
adv cp -a ${HOME}/src/${SERVICE}/system.sqlite nest/
adv cp -a ${HOME}/var/db/yaal/keys/* nest/var/db/yaal/keys/
adv cp -a ${HOME}/src/yaal/_aux/set-limits.sh nest
adv conditional_immutable_off ${JAIL}/nest
adv conditional_umount
adv /bin/rm -rf ${JAIL}/*

adv mkdir -p nest/app
HECTOR_SETUP=`readlink ${HOME}/src/${SERVICE}/app/hector.xml`
adv cp -a ${HOME}/src/${SERVICE}/app/${HECTOR_SETUP} nest/app/hector.xml
APPS=$(xmlstarlet sel -T -t -m "/hector/applications/application[@load='true' and @code != '']" -o ${HOME}/src/cellar/web/ -v '@code' -n ${HOME}/src/${SERVICE}/app/${HECTOR_SETUP})
APPS="${APPS}\\n$(xmlstarlet sel -T -t -m "/hector/applications/application[@load='true' and not( @code )]" -o ${HOME}/src/cellar/web/ -v '@id' -n ${HOME}/src/${SERVICE}/app/${HECTOR_SETUP})"
APPS=$(echo "${APPS}" | sort -u)
echo "Installing applications: ${APPS}"
adv cp -af ${APPS} nest/app/
for ITEM in nest/app/* ; do
	if [ -f ${ITEM}/interface.xml ] ; then
		APP=$(basename ${ITEM})
		if [ -f ./build/${TARGET}/${APP}/1exec ] ; then
			adv /bin/rm -f nest/app/${APP}/activex
			adv cp -f ./build/${TARGET}/${APP}/1exec nest/app/${APP}/activex
			adv chmod 644 nest/app/${APP}/activex
		fi
	fi
done
adv cp -a ${HOME}/src/server/hector/setup.dtd nest/app/codestation
adv mkdir -p ${JAIL}/tmp/hector ${JAIL}/bin

adv mv nest ${JAIL}/
adv cp -H /bin/sh ${JAIL}/bin/sh
adv cp -H /usr/bin/launchtool ${JAIL}/bin/
adv chmod 1757 ${JAIL}/tmp
adv chmod 755 ${JAIL}/tmp/hector
adv chown -R root:root ${JAIL}/nest/
adv chown ${SERVICE}:service ${JAIL}/nest/ ${JAIL}/nest/system.sqlite ${JAIL}/tmp/hector
adv chmod -R a+rX ${JAIL}/bin ${JAIL}/nest/*
adv mkdir -p ${JAIL}/var/run/postgresql
adv chmod -R a+rX ${JAIL}/var
adv mount --bind /var/run/postgresql ${JAIL}/var/run/postgresql
adv makejail ./_deploy/jail-${DAEMON}.py
if [ ! -f ${JAIL}/etc/passwd ] ; then
	echo "Deployment failed!"
	exit 1
fi
adv /bin/rm -f ${JAIL}/nest/x_*
adv "grep service /etc/group > ${JAIL}/etc/group"
adv conditional_immutable_on ${JAIL}/nest
adv chattr -i ${JAIL}/nest ${JAIL}/nest/system.sqlite


